// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBlog.Models;

public partial class Post
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime PublishDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string FilteredContent { get; set; }

    public string Status { get; set; }

    public string Path { get; set; }

    public string OgTitle { get; set; }

    public string OgDescription { get; set; }

    public string OgKeywords { get; set; }

    public string OgImage { get; set; }
}